apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "jenkins1:build-pipeline,jenkins1:deploy-pipeline"
  name: test-quarkus-app
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "experimental automation pipeline v1"
  name: test-quarkus-app-spaced
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gh-actions
  description: backstage.io
  annotations:
    "github.com/project-slug": 'caugello/rhtap-gh-actions'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-internal
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '112757'
    "gitlab.com/instance": 'gitlab.internal.cee'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-dev
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '66599006'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-python
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '66590134'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-multi-ci
  description: backstage.io
  annotations:
    "github.com/project-slug": 'caugello/rhtap-gh-actions'
    "jenkins.io/job-full-name": "build-pipeline,deploy-pipeline"
    "gitlab.com/project-id": '112757'
    "gitlab.com/instance": 'gitlab.internal.cee'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-no-ci-configured
  description: backstage.io
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-gh-no-logs
  description: backstage.io
  annotations:
    "github.com/project-slug": 'karthikjeeyar/GHA-matrix-workflow'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-tpa-link
  description: backstage.io
  annotations:
    "github.com/project-slug": 'tnevrlka-rhtap/baz-gitops'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-fvmmug2cp-go
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '66632817'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-azure-pipelines
  description: backstage.io
  annotations:
    dev.azure.com/project: "shared-public"
    dev.azure.com/build-definition: "tnevrlka-rhtap.tssc-dev-source-azure"
    dev.azure.com/host-org: "dev.azure.com/rhtap-test"
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-azure-pipelines-live
  description: backstage.io
  annotations:
    dev.azure.com/project: "shared-public"
    dev.azure.com/build-definition: "tnevrlka-rhtap.azure-live"
    dev.azure.com/host-org: "dev.azure.com/rhtap-test"
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-azure-pipelines-katka
  description: backstage.io
  annotations:
    dev.azure.com/project: "shared-public"
    dev.azure.com/build-definition: "katka-rhtap.katka-node-azure"
    dev.azure.com/host-org: "dev.azure.com/rhtap-test"
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quay-repo-nodejs
  description: backstage.io
  annotations:
    "quay.io/repository-slug": 'caugello/single-nodejs-app'
    "github.com/project-slug": 'caugello/rhtap-gh-actions'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-azure-pipelines-no-definitions
  description: backstage.io
  annotations:
    dev.azure.com/project: "shared-public"
    dev.azure.com/build-definition: "rhtap-test.testazurepython0613a"
    dev.azure.com/host-org: "dev.azure.com/rhtap-test"
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tekton-demo
  namespace: development
  annotations:
    tekton.dev/cicd: 'true'
    # It's important that your Tekton CRs have this annotation. If not they wont appear.
    backstage.io/kubernetes-id: 'rhtap'
    backstage.io/kubernetes-namespace: 'tekton-pipelines'
spec:
  type: service
  lifecycle: production
  owner: janus-authors

