apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "build-pipeline,deploy-pipeline"
  name: test-quarkus-app
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "experimental automation pipeline v1"
  name: test-quarkus-app-spaced
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gh-actions
  description: backstage.io
  annotations:
    "github.com/project-slug": 'caugello/rhtap-gh-actions'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab
  description: backstage.io
  annotations:
    "gitlab.com/project-id": 112757
    "gitlab.com/instance": 'internal'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
