apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "build-pipeline,deploy-pipeline"
  name: test-quarkus-app
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "experimental automation pipeline v1"
  name: test-quarkus-app-spaced
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gh-actions
  description: backstage.io
  annotations:
    "github.com/project-slug": 'caugello/rhtap-gh-actions'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-internal
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '112757'
    "gitlab.com/instance": 'gitlab.internal.cee'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-dev
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '66599006'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-python
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '66590134'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-multi-ci
  description: backstage.io
  annotations:
    "github.com/project-slug": 'caugello/rhtap-gh-actions'
    "jenkins.io/job-full-name": "build-pipeline,deploy-pipeline"
    "gitlab.com/project-id": '112757'
    "gitlab.com/instance": 'gitlab.internal.cee'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-no-ci-configured
  description: backstage.io
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-gh-no-logs
  description: backstage.io
  annotations:
    "github.com/project-slug": 'karthikjeeyar/GHA-matrix-workflow'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-tpa-link
  description: backstage.io
  annotations:
    "github.com/project-slug": 'tnevrlka-rhtap/baz-gitops'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-quarkus-gitlab-fvmmug2cp-go
  description: backstage.io
  annotations:
    "gitlab.com/project-id": '66632817'
spec:
  type: service
  lifecycle: production
  owner: janus-authors
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-azure-pipelines
  description: backstage.io
  annotations:
    dev.azure.com/build-definition: "tnevrlka-rhtap.tssc-dev-source-azure"
    dev.azure.com/host-org: "dev.azure.com/rhtap-test"
spec:
  type: service
  lifecycle: production
  owner: janus-authors
  


