apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "calculator-app-pipeline"
  name: test-quarkus-app
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    "jenkins.io/job-full-name": "some-other-pipeline"
  name: test-quarkus-app-ws1
  description: An example of a Backstage application.
spec:
  type: service
  owner: janus-authors
  lifecycle: production
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: backstage.io
  annotations:
    github.com/project-slug: 'caugello/rhtap-gh-actions'
spec:
  type: website
  lifecycle: production
  owner: janus-authors
